name: 'Compile'
permissions: {}
on:
  workflow_call:
    # NOTE Here this isn't supported (yet?).
    # paths: ['**.el']
    inputs:
      # NOTE Because there is nothing like 'github.worflow.ref'.
      workflow_ref:
        description: 'Must be the same as "uses: ...@THIS"'
        default: main
        required: false
        type: string
env:
  pwd: ${{ github.event.repository.name }}
jobs:
  matrix:
    name: 'Get matrix'
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: 'Install Emacs'
        uses: purcell/setup-emacs@master
        with:
          version: 30.1
      - name: 'Install scripts'
        uses: actions/checkout@v4
        with:
          repository: emacscollective/workflows
          ref: ${{ inputs.workflow_ref }}
          path: _scripts
          persist-credentials: false
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@v4
        with:
          path: ${{ env.pwd }}
          persist-credentials: false
      - name: 'Get matrix'
        id: matrix
        working-directory: ${{ env.pwd }}
        run: |
          ../_scripts/bin/get-matrix >> $GITHUB_OUTPUT
          echo "• get-matrix: emacscollective/workflows@${{ inputs.workflow_ref }}"
  main:
    name: 'Compile using Emacs ${{ matrix.emacs }}'
    runs-on: ubuntu-24.04
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        emacs: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: 'Install Emacs'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs }}
      - name: 'Install scripts'
        uses: actions/checkout@v4
        with:
          repository: emacscollective/workflows
          ref: ${{ inputs.workflow_ref }}
          path: _scripts
          persist-credentials: false
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@v4
        with:
          path: ${{ env.pwd }}
          fetch-depth: 0
          persist-credentials: false
      - name: 'Install dependencies'
        working-directory: ${{ env.pwd }}
        run: ../_scripts/bin/install-deps
      - name: 'Compile'
        working-directory: ${{ env.pwd }}
        run: |
          touch check-declare
          make EMACS_ARGS='--eval "(progn \
          (load-file \"../_scripts/lib/compile.el\"))"' lisp
      - name: 'Compile (byte-compile-error-on-warn)'
        if: ${{ vars.byte_compile_error_on_warn != 'nil' }}
        working-directory: ${{ env.pwd }}
        run: |
          touch check-declare
          make EMACS_ARGS='--eval "(progn \
          (setq byte-compile-error-on-warn t) \
          ${{ vars.compile_error_settings }} \
          (load-file \"../_scripts/lib/compile.el\"))"' clean lisp
