name: 'Compile'
permissions: {}
on:
  workflow_call:
    # NOTE Here this isn't supported (yet?).
    # paths: ['**.el']
    inputs:
      # NOTE github.workflow_ref is the revision of the caller.
      workflow_ref:
        description: 'Must be the same as "uses: ...@THIS"'
        default: main
        required: false
        type: string
env:
  pwd: ${{ github.event.repository.name }}
jobs:
  matrix:
    name: 'Get matrix'
    runs-on: ubuntu-26.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: 'Install Emacs'
        uses: purcell/setup-emacs@34c6ded44899fd1bf74d2889558befd1750e61a7 # > v8
        with:
          version: 31.1
      - name: 'Install scripts'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: emacscollective/workflows
          ref: ${{ inputs.workflow_ref }}
          path: _scripts
          persist-credentials: false
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ${{ env.pwd }}
          persist-credentials: false
      - name: 'Get matrix'
        id: matrix
        working-directory: ${{ env.pwd }}
        env:
          WORKFLOW_REF: ${{ inputs.workflow_ref }}
        run: |
          ../_scripts/bin/get-matrix >> $GITHUB_OUTPUT
          echo "• get-matrix: emacscollective/workflows@${WORKFLOW_REF}"
  main:
    name: 'Compile using Emacs ${{ matrix.emacs }}'
    runs-on: ubuntu-26.04
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        emacs: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: 'Install Emacs'
        uses: purcell/setup-emacs@34c6ded44899fd1bf74d2889558befd1750e61a7 # > v8
        with:
          version: ${{ matrix.emacs }}
      - name: 'Install scripts'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: emacscollective/workflows
          ref: ${{ inputs.workflow_ref }}
          path: _scripts
          persist-credentials: false
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ${{ env.pwd }}
          fetch-depth: 0
          persist-credentials: false
      - name: 'Install dependencies'
        working-directory: ${{ env.pwd }}
        run: |
          ../_scripts/bin/install-deps
      - name: 'Compile'
        working-directory: ${{ env.pwd }}
        run: |
          make EMACS_ARGS='--eval "(progn \
          (load-file \"${{ github.workspace }}/_scripts/lib/compile.el\"))"' \
          lisp
      - name: 'Compile (byte-compile-error-on-warn)'
        if: ${{ vars.byte_compile_error_on_warn != 'nil' }}
        working-directory: ${{ env.pwd }}
        env:
          COMPILE_ERROR_SETTINGS: ${{ vars.compile_error_settings }}
        run: |
          make EMACS_ARGS='--eval "(progn \
          (setq byte-compile-error-on-warn t) \
          ${COMPILE_ERROR_SETTINGS} \
          (load-file \"${{ github.workspace }}/_scripts/lib/compile.el\"))"' \
          clean lisp
