name: 'Manual'
permissions: {}
on:
  workflow_call:
    secrets:
      rclone_config:
        required: true
jobs:
  manual:
    name: 'Generate manual'
    runs-on: ubuntu-26.04
    steps:
      - name: 'Install emacs'
        uses: purcell/setup-emacs@34c6ded44899fd1bf74d2889558befd1750e61a7 # > v8
        with:
          version: 31.1
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y texlive rclone
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 'Set version'
        if: github.ref_type == 'branch'
        run: |
          v=$(git describe)
          for manual in docs/*.org; do
            sed -i -E $manual \
                -e "s|^(#\+subtitle: for version) .*|\1 $v|" \
                -e "s|^(This manual is for [^ ]* version).*|\1 $v.|"
          done
      - name: 'Configure rclone'
        env:
          CONFIG: ${{ secrets.rclone_config }}
        run: |
          printf "${CONFIG}" | base64 --decode > "${RUNNER_TEMP}/rclone.conf"
      - name: 'Publish manual'
        env:
          RCLONE_ARGS: -v --config "${RUNNER_TEMP}/rclone.conf"
        run: |
          make ${{ github.ref_type == 'tag' && 'release' || 'publish' }}
