name: 'Publish'
permissions: {}
on:
  workflow_call:
    secrets:
      rclone_config:
        required: true
jobs:
  publish:
    name: 'Publish page'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Install emacs'
        uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # v8
        with:
          version: 30.1
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y rclone
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 'Configure rclone'
        env:
          CONFIG: ${{ secrets.rclone_config }}
        run: |
          printf "${CONFIG}" | base64 --decode > "${RUNNER_TEMP}/rclone.conf"
      - name: 'Generate page'
        run: |
          make html
      - name: 'Publish page'
        env:
          RCLONE_ARGS: -v --config "${RUNNER_TEMP}/rclone.conf"
        run: |
          make publish
