name: 'Readme'
permissions: {}
on:
  workflow_call:
    secrets:
      rclone_config:
        required: true
jobs:
  manual:
    name: 'Export readme'
    runs-on: ubuntu-26.04
    steps:
      - name: 'Install emacs'
        uses: purcell/setup-emacs@34c6ded44899fd1bf74d2889558befd1750e61a7 # > v8
        with:
          version: 31.1
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y rclone
      - name: 'Checkout ${{ github.repository }}'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 'Export readme'
        run: |
          make html
      - name: 'Configure rclone'
        env:
          CONFIG: ${{ secrets.rclone_config }}
        run: |
          printf "${CONFIG}" | base64 --decode > "${RUNNER_TEMP}/rclone.conf"
      - name: 'Publish readme'
        env:
          RCLONE_ARGS: -v --config "${RUNNER_TEMP}/rclone.conf"
        run: |
          make publish
